<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BindingsDir>$(ProjectDir)\lib\bindings</BindingsDir>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="OpenTK.Compute">
      <HintPath>$(VINTAGE_STORY)\Lib\OpenTK.Compute.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenTK.Core">
      <HintPath>$(VINTAGE_STORY)\Lib\OpenTK.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenTK.Graphics">
      <HintPath>$(VINTAGE_STORY)\Lib\OpenTK.Graphics.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenTK.Input">
      <HintPath>$(VINTAGE_STORY)\Lib\OpenTK.Input.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenTK.Mathematics">
      <HintPath>$(VINTAGE_STORY)\Lib\OpenTK.Mathematics.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenTK.Windowing.Common">
      <HintPath>$(VINTAGE_STORY)\Lib\OpenTK.Windowing.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenTK.Windowing.Desktop">
      <HintPath>$(VINTAGE_STORY)\Lib\OpenTK.Windowing.Desktop.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenTK.Windowing.GraphicsLibraryFramework">
      <HintPath>$(VINTAGE_STORY)\Lib\OpenTK.Windowing.GraphicsLibraryFramework.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ImGui.NET">
      <HintPath>$(BindingsDir)\ImGui.NET.dll</HintPath>
    </Reference>
    <Reference Include="ImGuizmo.NET">
      <HintPath>$(BindingsDir)\ImGuizmo.NET.dll</HintPath>
    </Reference>
    <Reference Include="ImNodes.NET">
      <HintPath>$(BindingsDir)\ImNodes.NET.dll</HintPath>
    </Reference>
    <Reference Include="ImPlot.NET">
      <HintPath>$(BindingsDir)\ImPlot.NET.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>